Create hosting-on-linux-server
AnIdiotsGuide/discordjs-bot-guide pull request #130
Opened 2020-11-28 10:22 UTC by ookamicodes

This would be a good guide if someone needs a 24/7 hosting with good performance.

2021-01-03 17:26 UTC, almeidx requested changes
Missing the `.md` file extension

2021-02-18 11:20 UTC, kyranet requested changes

2021-02-18 11:20 UTC, kyranet commented on other-guides/hosting-on-linux-server
> +The best way to host your bot is on a Linux Server (or simply said: just a virtual server. Its also for bare metal servers).
Linux Server != Virtual Server.

2021-02-18 11:20 UTC, kyranet commented on other-guides/hosting-on-linux-server
> +- A Linux Server with a stable version, node, npm, git, pm2.
Stable version?? What does that exactly mean?? You can recommend **Debian 10**, as it's a very stable, robust, and minimal Linux distro, best suited for servers.

2021-02-18 11:20 UTC, kyranet commented on other-guides/hosting-on-linux-server
> +- Github repository from your bot (privat).
GitHub isn't needed, people can use other services (Docker, GitLab, BitBucket, SourceForge, Gitea, self-hosted...), or even, upload the files directly.

2021-02-18 11:20 UTC, kyranet commented on other-guides/hosting-on-linux-server
> +The best way to do that is with root access. If its root access the username would be `root`.
While the default user is `root`, it's very unwise to use it, as a vulnerability in your bot or one of its services can put the entire system at risk.

Please recommend creating a new user with a password different to `root`.

2021-02-18 11:20 UTC, kyranet commented on other-guides/hosting-on-linux-server
> +The first step you do is to login into your Linux Server. You can use a SSH Client, with Windows CMD `ssh (username)@(ip)` or on macOS ssh 192.168.2.30 -l (username)`
Not necessary for Windows, you can set up `%UserProfile%/.ssh/config` with something such as:

```yaml
Host my-server
  HostName 192.168.1.1
  Port 22
  User my-user
```

And then when you do `ssh my-server`, it automatically logs in.

2021-02-18 11:20 UTC, kyranet commented on other-guides/hosting-on-linux-server
> +and type next `npm i`. You need to reinstall that because the Linux got a other compiler then your windows computer (this is because there are diffrent OS). After you installed node_modules,
You should never commit `node_modules`, in fact, you must add it to `.gitignore`.

2021-02-18 11:20 UTC, kyranet commented on other-guides/hosting-on-linux-server
> +To monitor your application type `pm2 monit`. You can see awesome things like CPU/RAM usage, process lists, logs and more.
There are more alternatives to `pm2`, I don't agree a "hosting on a Linux Server" guide should be biased towards very specific tools.

2021-03-01 13:36 UTC, eslachance commented
All in all there's too much wrong with this PR to be allowed. 
- You say "Linux" but there's a hundred distros so it's not precise enough
- There's too much bias towards specific tools
- There's a *ton* of very bad suggestions here like being root on everything or comitting your node_modules folder
- it's missing *actual* information on how to do things even if all the above were fixed.

Sorry, I can't accept this at all.

2021-03-01 13:36 UTC, closed without merging