guide: fix for and improvements to FAQ: presence and status
AnIdiotsGuide/discordjs-bot-guide pull request #40
Opened 2018-10-05 11:28 UTC by almostSouji

Fixes FAQ `.setActivity()` example and expands it with `.setPresence()` and a streaming example + help text for an easy reference in case the question comes up.

2018-10-08 14:26 UTC, Stitch07 requested changes

2018-10-08 14:26 UTC, Stitch07 commented on frequently-asked-questions.md
> +    client.user.setActivity("with my code", { type: "PLAYING"})
Type defaults to PLAYING.

2018-10-08 14:33 UTC, almostSouji commented on frequently-asked-questions.md
> +    client.user.setActivity("with my code", { type: "PLAYING"})
true, should better be used with non-default, adapted

2018-10-08 14:33 UTC, Stitch07 approved these changes

2018-10-13 18:48 UTC, ChineseMarc approved these changes

2018-10-15 02:25 UTC, merged