Update raw-events.md
AnIdiotsGuide/discordjs-bot-guide pull request #96
Opened 2020-04-20 01:24 UTC by Jonyk56

2020-04-20 01:40 UTC, iAmZiNc commented on coding-guides/raw-events.md
>      channel.fetchMessage(packet.d.message_id).then(message => {
fetchMessage is not a Channel method anymore. Moved into Managers.

2020-04-20 01:44 UTC, eslachance commented
While this update is technically correct, v12 offers partials now, which means the entire idea of having to use raw events become moot in the case of reactions particularly. Instead of just updating the existing code I think we should review this page to use partials instead.

2020-04-20 01:51 UTC, eslachance requested changes

2020-04-20 01:51 UTC, eslachance commented on coding-guides/raw-events.md
>      if (!['MESSAGE_REACTION_ADD', 'MESSAGE_REACTION_REMOVE'].includes(packet.t)) return;
Edit this to use partials instead to take advantage of the new v12 features

2020-04-25 02:52 UTC, iAmZiNc commented
This file has been updated complete in #102. This PR can be closed and a new one for rewrite to use partials could be forked from that PR. @eslachance

2020-04-25 12:52 UTC, eslachance commented
No update from contributor after change requests and conversations.

2020-04-25 12:52 UTC, closed without merging